- name: Configure NGINX for peppermint-devops.be
  hosts: peppermint-server
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Configure NGINX for peppermint-devops.be
      copy:
        dest: /etc/nginx/sites-available/peppermint-devops
        content: |
          server {
              listen 80;
              server_name peppermint-devops.be;

              root /var/www/html;
              index index.html;

              location /.well-known/acme-challenge/ {
                  root /var/www/html;
                  default_type "text/plain";
              }

              location / {
                  try_files $uri $uri/ =404;
              }
          }
      notify: Reload NGINX

    - name: Enable NGINX site configuration
      file:
        src: /etc/nginx/sites-available/peppermint-devops
        dest: /etc/nginx/sites-enabled/peppermint-devops
        state: link

    - name: Remove default site configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

  handlers:
    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
