---
- name: Deploy Peppermint Application
  hosts: peppermint
  become: true
  tasks:

    # Ensure Docker and Docker Compose are installed (previous tasks)
    - name: Install Docker and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    # Add user to docker group
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes

    # Create Docker Compose file for Peppermint
    - name: Create Docker Compose file
      copy:
        dest: /opt/peppermint/docker-compose.yml
        content: |
          version: '3.1'

          services:
            peppermint_postgres:
              container_name: peppermint_postgres
              image: postgres:latest
              restart: always
              volumes:
                - pgdata:/var/lib/postgresql/data
              environment:
                POSTGRES_USER: peppermint
                POSTGRES_PASSWORD: 1234
                POSTGRES_DB: peppermint

            peppermint:
              container_name: peppermint
              image: pepperlabs/peppermint:latest
              ports:
                - "3000:3000"
                - "5003:5003"
              restart: always
              depends_on:
                - peppermint_postgres
              environment:
                DB_USERNAME: "peppermint"
                DB_PASSWORD: "1234"
                DB_HOST: "peppermint_postgres"
                SECRET: 'peppermint4life'

          volumes:
            pgdata:

    # Start Docker Compose
    - name: Start Peppermint application with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/peppermint

    # Verify Docker containers are running
    - name: Check running containers
      command: docker ps
      register: running_containers
      changed_when: false

    - name: Output running containers
      debug:
        var: running_containers.stdout_lines
